packages:
  - apps/*
  - packages/*

catalog:
  '@2digits/eslint-config': 4.13.6
  '@2digits/prettier-config': 4.0.17
  '@2digits/tsconfig': 0.8.4
  '@babel/core': ^7.28.5
  '@babel/plugin-transform-react-jsx': ^7.27.1
  '@expo/vector-icons': ^15.0.3
  '@payloadcms/db-sqlite': 3.62.0
  '@payloadcms/drizzle': 3.62.0
  '@payloadcms/next': 3.62.0
  '@payloadcms/ui': 3.62.0
  '@react-navigation/bottom-tabs': ^7.4.0
  '@react-navigation/elements': ^2.6.3
  '@react-navigation/native': ^7.1.8
  '@t3-oss/env-core': 0.13.8
  '@tanstack/react-query': ^5.90.10
  '@types/babel__core': ^7.20.5
  '@types/node': 24.10.1
  '@types/react': 19.2.6
  '@types/react-dom': 19.2.3
  babel-plugin-react-compiler: 19.1.0-rc.3
  babel-preset-expo: ^54.0.7
  date-fns: 4.1.0
  eslint: 9.39.1
  expo: ~54.0.25
  expo-build-properties: ^1.0.9
  expo-constants: ~18.0.10
  expo-dev-client: ^6.0.18
  expo-doctor: ^1.17.11
  expo-font: ~14.0.9
  expo-haptics: ~15.0.7
  expo-image: ~3.0.10
  expo-linking: ~8.0.9
  expo-router: ~6.0.15
  expo-splash-screen: ~31.0.11
  expo-status-bar: ~3.0.8
  expo-symbols: ~1.0.7
  expo-system-ui: ~6.0.8
  expo-web-browser: ~15.0.9
  graphql: 16.12.0
  jiti: 2.6.1
  nativewind: ^4.2.1
  next: 16.0.3
  payload: 3.62.0
  payload-auth: 1.2.0
  prettier: 3.6.2
  react: 19.2.0
  react-compiler-runtime: ^1.0.0
  react-dom: 19.2.0
  react-native: 0.80.2
  react-native-css-interop: ^0.2.1
  react-native-gesture-handler: ~2.28.0
  react-native-reanimated: ~4.1.1
  react-native-safe-area-context: ~5.6.0
  react-native-screens: ~4.16.0
  react-native-web: ~0.21.0
  react-native-worklets: 0.5.1
  sharp: 0.34.5
  tailwindcss: ^3.4.17
  tsdown: 0.16.6
  turbo: 2.6.1
  typescript: 5.9.2
  ufo: 1.6.1
  vercel: 48.8.0
  zod: 4.1.12

catalogMode: prefer

catalogs:
  conflicts_react_19_1_0:
    react: 19.1.0

cleanupUnusedCatalogs: true

preferWorkspacePackages: true
